### ISSUE TITLE
"review" chokes on old snapshots in test directory

### ISSUE THREAD

**Issue by aberres** [vberlier/pytest-insta#15]
**Steps to reproduce**

- Create a snapshot like `snapshot('audit.txt')`
- Run test
- Rename snapshot like like `snapshot('audit.json')`
- Run test
- Now run test with `--insta review`

**Expected behavior**

Things work just fie.
Review works as expected or alternatively I am instructed to do some kind of cleanup.

**Actual behavior**
 
As `audit.txt` is still existing in the cache folder the last pytest call fails with an error like this:

`FileNotFoundError: [Errno 2] No such file or directory: 'flaskapp/snapshots/views__cm_views__audit.txt'`

Running `--insta clear` fixes the issue.

For new users, this behavior can be quite unexpected. Especially as one might not even remember anymore that a snapshot with the unexpected name once existed.

**Comment by vberlier** [comment]
I managed to reproduce the issue. To fix this I'm going to make the review tool clear recordings that are no longer associated with any snapshot. This should make renaming snapshots completely transparent.

**Comment by vberlier** [comment]
Alright, just released this. Let me know if you encounter any other problem 👍

**Comment by aberres** [comment]
Perfect, thanks!

I am planning to use pytest-insta for quite a bunch of tests. Will tell if anything comes up.
