### ISSUE TITLE
Partial matching functionality?

### ISSUE THREAD

**Issue by cameronmaske** [vberlier/pytest-insta#85]
Hi @vberlier

First off, what a wonderful library! Thanks for the time and effort you've put into this, it really scratches an itch I've experienced when it comes to testing in the Python world. 

I wanted to discuss if there is interest in extending the functionality (which I'd be more than happy to contribute the work towards) to allow for setting "partial" expectations in a snapshot. 

Here's a use case to hopefully illustrate that sort of functionality. 

I often find myself writing tests like this....

```python
def test_posts_detail(api_client):
    post = PostFactory(title="Amazing deal!", body="Don't miss out", published_at=date(2021, 1, 1))

    response = api_client.get(f"/posts/{post.id}/")

    assert response.json() == {
        "id": str(post.id), 
        "title": "Amazing deal!",
        "body": "Don't miss out", 
        "published_at": "2021-1-1"
    }
```

It's super useful to be able this against a snapshot. Especially as project go on, and API change over time, the review process really help keep things manageable. 
However, there is one snag, most of all the fields are "frozen" but in this case the `id` is dynamic. I can't control what it will be (i.e depends on how many tests, what operation happened before, etc). 

I would love the ability to provide the snapshot with a few selected expectations, i.e something like this....

```python
def test_posts_detail(api_client, snapshot):
    post = PostFactory(title="Amazing deal!", body="Don't miss out", published_at=date(2021, 1, 1))

    response = api_client.get(f"/posts/{post.id}/")

    assert snapshot("json", {"id": str(post.id)}) == response.json()
```

In this case, the `id` will always be updated and set at runtime in the test, but the rest of are snapshotted.

**Comment by vberlier** [comment]
Glad you think this is useful! The project is inspired by the original Rust version which provides [redactions](https://insta.rs/docs/redactions/) to avoid storing non stable values in snapshots. However, because the API is a bit more flexible thanks to Python you can simply modify or remove fields that are not stable before snapshotting.

```python
def test_posts_detail(api_client, snapshot):
    post = PostFactory(title="Amazing deal!", body="Don't miss out", published_at=date(2021, 1, 1))

    response = api_client.get(f"/posts/{post.id}/")
    data = response.json()
    data["id"] = ""  # or remove it with `del data["id"]`

    assert snapshot("json") == data
```

If you end up doing this a lot and you need something similar to the redactions feature you can really easily write your own helper to make your responses stable.

```python
SUBSTITUTIONS = {
    ("id",): "",
    ("billing", "details"): {},  # can substitute entire json objects
    ("api_keys", "*", "token"): "",  # use "*" to select all elements in a list
}

def stable(data, subst, path=()):
    for suffix, replacement in subst.items():
        if path[-len(suffix) :] == suffix:
            return replacement
    if isinstance(data, dict):
        return {key: stable(value, subst, (*path, key)) for key, value in data.items()}
    if isinstance(data, list):
        return [stable(value, subst, (*path, "*")) for value in data]
    return data

assert snapshot("json") == stable(response.json(), SUBSTITUTIONS)
```

The function will select matching fields and replace them with a stable value. Feel free to tweak it according to your use-case.

Hope this helps!
